"""Language picker data + translations for the most visible bot messages.

Anything without a translation here falls back to the bot's original text,
so a language can be extended key by key without breaking anything.
"""

# (code, button label) — shown 2 per row, in this order (same order as the reference bot)
LANGS = [
    ("en", "🇺🇸 English"), ("ru", "🇷🇺 Русский"),
    ("ar", "العربية 🇸🇦"), ("hi", "🇮🇳 हिन्दी"),
    ("zh", "🇨🇳 中文"), ("es", "🇪🇸 Español"),
    ("fr", "🇫🇷 Français"), ("bn", "🇧🇩 বাংলা"),
    ("pt", "🇵🇹 Português"), ("ur", "اردو 🇵🇰"),
    ("id", "🇮🇩 Bahasa Indonesia"), ("ja", "🇯🇵 日本語"),
    ("fil", "🇵🇭 Filipino"), ("ha", "🇳🇬 Hausa"),
    ("vi", "🇻🇳 Tiếng Việt"), ("it", "🇮🇹 Italiano"),
    ("de", "🇩🇪 Deutsch"), ("tr", "🇹🇷 Türkçe"),
    ("ko", "🇰🇷 한국어"), ("pl", "🇵🇱 Polski"),
    ("uk", "🇺🇦 Українська"), ("fa", "فارسی 🇮🇷"),
    ("th", "🇹🇭 ไทย"), ("uz", "🇺🇿 O‘zbek"),
    ("kk", "🇰🇿 Қазақ"),
]

LANG_NAMES = {
    "en": "English", "hi": "हिन्दी", "ur": "اردو", "ar": "العربية", "es": "Español",
    "fr": "Français", "id": "Bahasa Indonesia", "ru": "Русский", "tr": "Türkçe",
    "zh": "中文", "pt": "Português", "fa": "فارسی", "vi": "Tiếng Việt",
    "ko": "한국어", "ja": "日本語",
    "bn": "বাংলা", "fil": "Filipino", "ha": "Hausa", "it": "Italiano", "de": "Deutsch",
    "pl": "Polski", "uk": "Українська", "th": "ไทย", "uz": "O‘zbek", "kk": "Қазақ",
}

PICKER_TEXT = "🌐 <b>Choose Your Preferred Language:</b>\nSelect a language below to get started!"

# keys: lang_set fetching avail tap trim_btn trim_dur trim_ask trim_ex trim_fmt trim_order
#       trim_long trim_pick expired not_yours cancel_btn dl_cancelled
TR = {
    "en": {
        "lang_set": "✅ Language set to {name}.",
        "fetching": "🔍 <b>Fetching video info...</b>",
        "avail": "Available qualities:",
        "tap": "Tap a quality below to download:",
        "trim_btn": "✂️ Video Trim",
        "trim_dur": "Video duration",
        "trim_ask": "Please send the desired time range in format:",
        "trim_ex": "Example",
        "trim_fmt": "❌ <b>Wrong format.</b>\n\nSend it like this:",
        "trim_order": "❌ <b>Start time must be earlier than end time.</b>",
        "trim_long": "❌ <b>End time is beyond the video duration ({dur}).</b>",
        "trim_pick": "Tap a quality below to download the trimmed clip:",
        "expired": "Link expired — please send it again.",
        "not_yours": "This isn't your request.",
        "cancel_btn": "❌ Cancel",
        "dl_cancelled": "🛑 <b>Download cancelled.</b>",
    },
    "hi": {
        "lang_set": "✅ भाषा {name} सेट हो गई।",
        "fetching": "🔍 <b>वीडियो की जानकारी ला रहा हूँ...</b>",
        "avail": "उपलब्ध क्वालिटी:",
        "tap": "डाउनलोड के लिए नीचे क्वालिटी चुनें:",
        "trim_btn": "✂️ वीडियो ट्रिम",
        "trim_dur": "वीडियो की अवधि",
        "trim_ask": "कृपया इस फॉर्मैट में समय सीमा भेजें:",
        "trim_ex": "उदाहरण",
        "trim_fmt": "❌ <b>फॉर्मैट गलत है।</b>\n\nइस तरह भेजें:",
        "trim_order": "❌ <b>शुरुआती समय, अंतिम समय से पहले होना चाहिए।</b>",
        "trim_long": "❌ <b>अंतिम समय वीडियो की अवधि ({dur}) से ज़्यादा है।</b>",
        "trim_pick": "ट्रिम की हुई क्लिप डाउनलोड करने के लिए नीचे क्वालिटी चुनें:",
        "expired": "लिंक की समय-सीमा खत्म हो गई — दोबारा भेजें।",
        "not_yours": "यह आपका रिक्वेस्ट नहीं है।",
        "cancel_btn": "❌ रद्द करें",
        "dl_cancelled": "🛑 <b>डाउनलोड रद्द किया गया।</b>",
    },
    "ur": {
        "lang_set": "✅ زبان {name} پر سیٹ ہو گئی۔",
        "fetching": "🔍 <b>ویڈیو کی معلومات حاصل کی جا رہی ہیں...</b>",
        "avail": "دستیاب کوالٹیز:",
        "tap": "ڈاؤن لوڈ کے لیے نیچے کوالٹی منتخب کریں:",
        "trim_btn": "✂️ ویڈیو ٹرِم",
        "trim_dur": "ویڈیو کا دورانیہ",
        "trim_ask": "براہِ کرم مطلوبہ وقت کی حد اس فارمیٹ میں بھیجیں:",
        "trim_ex": "مثال",
        "trim_fmt": "❌ <b>فارمیٹ غلط ہے۔</b>\n\nاس طرح بھیجیں:",
        "trim_order": "❌ <b>شروع کا وقت اختتامی وقت سے پہلے ہونا چاہیے۔</b>",
        "trim_long": "❌ <b>اختتامی وقت ویڈیو کے دورانیے ({dur}) سے زیادہ ہے۔</b>",
        "trim_pick": "ٹرِم کی ہوئی کلپ ڈاؤن لوڈ کرنے کے لیے نیچے کوالٹی منتخب کریں:",
        "expired": "لنک کی میعاد ختم ہو گئی — دوبارہ بھیجیں۔",
        "not_yours": "یہ آپ کی درخواست نہیں ہے۔",
        "cancel_btn": "❌ منسوخ کریں",
        "dl_cancelled": "🛑 <b>ڈاؤن لوڈ منسوخ کر دیا گیا۔</b>",
    },
    "ar": {
        "lang_set": "✅ تم ضبط اللغة على {name}.",
        "fetching": "🔍 <b>جارٍ جلب معلومات الفيديو...</b>",
        "avail": "الجودات المتاحة:",
        "tap": "اضغط على جودة أدناه للتحميل:",
        "trim_btn": "✂️ قص الفيديو",
        "trim_dur": "مدة الفيديو",
        "trim_ask": "يرجى إرسال النطاق الزمني المطلوب بالصيغة:",
        "trim_ex": "مثال",
        "trim_fmt": "❌ <b>الصيغة غير صحيحة.</b>\n\nأرسله هكذا:",
        "trim_order": "❌ <b>يجب أن يكون وقت البداية قبل وقت النهاية.</b>",
        "trim_long": "❌ <b>وقت النهاية يتجاوز مدة الفيديو ({dur}).</b>",
        "trim_pick": "اضغط على جودة أدناه لتحميل المقطع المقصوص:",
        "expired": "انتهت صلاحية الرابط — أرسله مرة أخرى.",
        "not_yours": "هذا الطلب ليس لك.",
        "cancel_btn": "❌ إلغاء",
        "dl_cancelled": "🛑 <b>تم إلغاء التحميل.</b>",
    },
    "es": {
        "lang_set": "✅ Idioma configurado: {name}.",
        "fetching": "🔍 <b>Obteniendo información del video...</b>",
        "avail": "Calidades disponibles:",
        "tap": "Toca una calidad abajo para descargar:",
        "trim_btn": "✂️ Recortar video",
        "trim_dur": "Duración del video",
        "trim_ask": "Envía el rango de tiempo deseado con este formato:",
        "trim_ex": "Ejemplo",
        "trim_fmt": "❌ <b>Formato incorrecto.</b>\n\nEnvíalo así:",
        "trim_order": "❌ <b>El inicio debe ser anterior al final.</b>",
        "trim_long": "❌ <b>El final supera la duración del video ({dur}).</b>",
        "trim_pick": "Toca una calidad abajo para descargar el clip recortado:",
        "expired": "El enlace expiró — envíalo de nuevo.",
        "not_yours": "Esta solicitud no es tuya.",
        "cancel_btn": "❌ Cancelar",
        "dl_cancelled": "🛑 <b>Descarga cancelada.</b>",
    },
    "fr": {
        "lang_set": "✅ Langue définie : {name}.",
        "fetching": "🔍 <b>Récupération des infos de la vidéo...</b>",
        "avail": "Qualités disponibles :",
        "tap": "Touchez une qualité ci-dessous pour télécharger :",
        "trim_btn": "✂️ Couper la vidéo",
        "trim_dur": "Durée de la vidéo",
        "trim_ask": "Envoyez la plage de temps souhaitée au format :",
        "trim_ex": "Exemple",
        "trim_fmt": "❌ <b>Format incorrect.</b>\n\nEnvoyez-le ainsi :",
        "trim_order": "❌ <b>Le début doit être avant la fin.</b>",
        "trim_long": "❌ <b>La fin dépasse la durée de la vidéo ({dur}).</b>",
        "trim_pick": "Touchez une qualité ci-dessous pour télécharger l'extrait :",
        "expired": "Lien expiré — renvoyez-le.",
        "not_yours": "Cette demande n'est pas la vôtre.",
        "cancel_btn": "❌ Annuler",
        "dl_cancelled": "🛑 <b>Téléchargement annulé.</b>",
    },
    "id": {
        "lang_set": "✅ Bahasa diatur ke {name}.",
        "fetching": "🔍 <b>Mengambil info video...</b>",
        "avail": "Kualitas tersedia:",
        "tap": "Ketuk kualitas di bawah untuk mengunduh:",
        "trim_btn": "✂️ Potong Video",
        "trim_dur": "Durasi video",
        "trim_ask": "Kirim rentang waktu yang diinginkan dengan format:",
        "trim_ex": "Contoh",
        "trim_fmt": "❌ <b>Format salah.</b>\n\nKirim seperti ini:",
        "trim_order": "❌ <b>Waktu mulai harus lebih awal dari waktu selesai.</b>",
        "trim_long": "❌ <b>Waktu selesai melebihi durasi video ({dur}).</b>",
        "trim_pick": "Ketuk kualitas di bawah untuk mengunduh klip hasil potongan:",
        "expired": "Tautan kedaluwarsa — kirim ulang.",
        "not_yours": "Ini bukan permintaanmu.",
        "cancel_btn": "❌ Batal",
        "dl_cancelled": "🛑 <b>Unduhan dibatalkan.</b>",
    },
    "ru": {
        "lang_set": "✅ Язык установлен: {name}.",
        "fetching": "🔍 <b>Получаю информацию о видео...</b>",
        "avail": "Доступное качество:",
        "tap": "Выберите качество ниже для загрузки:",
        "trim_btn": "✂️ Обрезка видео",
        "trim_dur": "Длительность видео",
        "trim_ask": "Отправьте нужный диапазон времени в формате:",
        "trim_ex": "Пример",
        "trim_fmt": "❌ <b>Неверный формат.</b>\n\nОтправьте так:",
        "trim_order": "❌ <b>Начало должно быть раньше конца.</b>",
        "trim_long": "❌ <b>Конец превышает длительность видео ({dur}).</b>",
        "trim_pick": "Выберите качество ниже, чтобы скачать обрезанный фрагмент:",
        "expired": "Ссылка устарела — отправьте её снова.",
        "not_yours": "Это не ваш запрос.",
        "cancel_btn": "❌ Отмена",
        "dl_cancelled": "🛑 <b>Загрузка отменена.</b>",
    },
    "tr": {
        "lang_set": "✅ Dil {name} olarak ayarlandı.",
        "fetching": "🔍 <b>Video bilgisi alınıyor...</b>",
        "avail": "Mevcut kaliteler:",
        "tap": "İndirmek için aşağıdan bir kalite seçin:",
        "trim_btn": "✂️ Video Kırp",
        "trim_dur": "Video süresi",
        "trim_ask": "Lütfen istediğiniz zaman aralığını şu biçimde gönderin:",
        "trim_ex": "Örnek",
        "trim_fmt": "❌ <b>Biçim yanlış.</b>\n\nŞöyle gönderin:",
        "trim_order": "❌ <b>Başlangıç, bitişten önce olmalı.</b>",
        "trim_long": "❌ <b>Bitiş, video süresini ({dur}) aşıyor.</b>",
        "trim_pick": "Kırpılan klibi indirmek için aşağıdan bir kalite seçin:",
        "expired": "Bağlantının süresi doldu — tekrar gönderin.",
        "not_yours": "Bu istek size ait değil.",
        "cancel_btn": "❌ İptal",
        "dl_cancelled": "🛑 <b>İndirme iptal edildi.</b>",
    },
    "zh": {
        "lang_set": "✅ 语言已设置为 {name}。",
        "fetching": "🔍 <b>正在获取视频信息...</b>",
        "avail": "可用画质:",
        "tap": "点击下方画质开始下载:",
        "trim_btn": "✂️ 视频剪辑",
        "trim_dur": "视频时长",
        "trim_ask": "请按以下格式发送所需的时间范围:",
        "trim_ex": "示例",
        "trim_fmt": "❌ <b>格式错误。</b>\n\n请按以下方式发送:",
        "trim_order": "❌ <b>开始时间必须早于结束时间。</b>",
        "trim_long": "❌ <b>结束时间超出视频时长({dur})。</b>",
        "trim_pick": "点击下方画质下载剪辑片段:",
        "expired": "链接已过期,请重新发送。",
        "not_yours": "这不是你的请求。",
        "cancel_btn": "❌ 取消",
        "dl_cancelled": "🛑 <b>下载已取消。</b>",
    },
    "pt": {
        "lang_set": "✅ Idioma definido: {name}.",
        "fetching": "🔍 <b>Obtendo informações do vídeo...</b>",
        "avail": "Qualidades disponíveis:",
        "tap": "Toque em uma qualidade abaixo para baixar:",
        "trim_btn": "✂️ Cortar vídeo",
        "trim_dur": "Duração do vídeo",
        "trim_ask": "Envie o intervalo de tempo desejado no formato:",
        "trim_ex": "Exemplo",
        "trim_fmt": "❌ <b>Formato incorreto.</b>\n\nEnvie assim:",
        "trim_order": "❌ <b>O início deve ser anterior ao fim.</b>",
        "trim_long": "❌ <b>O fim ultrapassa a duração do vídeo ({dur}).</b>",
        "trim_pick": "Toque em uma qualidade abaixo para baixar o trecho cortado:",
        "expired": "Link expirado — envie novamente.",
        "not_yours": "Esta solicitação não é sua.",
        "cancel_btn": "❌ Cancelar",
        "dl_cancelled": "🛑 <b>Download cancelado.</b>",
    },
    "fa": {
        "lang_set": "✅ زبان روی {name} تنظیم شد.",
        "fetching": "🔍 <b>در حال دریافت اطلاعات ویدیو...</b>",
        "avail": "کیفیت‌های موجود:",
        "tap": "برای دانلود، یکی از کیفیت‌های زیر را بزنید:",
        "trim_btn": "✂️ برش ویدیو",
        "trim_dur": "مدت ویدیو",
        "trim_ask": "لطفاً بازه زمانی دلخواه را با این قالب بفرستید:",
        "trim_ex": "مثال",
        "trim_fmt": "❌ <b>قالب نادرست است.</b>\n\nاین‌طور بفرستید:",
        "trim_order": "❌ <b>زمان شروع باید قبل از زمان پایان باشد.</b>",
        "trim_long": "❌ <b>زمان پایان از مدت ویدیو ({dur}) بیشتر است.</b>",
        "trim_pick": "برای دانلود کلیپ برش‌خورده، یکی از کیفیت‌های زیر را بزنید:",
        "expired": "لینک منقضی شد — دوباره بفرستید.",
        "not_yours": "این درخواست مال شما نیست.",
        "cancel_btn": "❌ لغو",
        "dl_cancelled": "🛑 <b>دانلود لغو شد.</b>",
    },
    "vi": {
        "lang_set": "✅ Đã đặt ngôn ngữ: {name}.",
        "fetching": "🔍 <b>Đang lấy thông tin video...</b>",
        "avail": "Chất lượng khả dụng:",
        "tap": "Chạm vào một chất lượng bên dưới để tải:",
        "trim_btn": "✂️ Cắt video",
        "trim_dur": "Thời lượng video",
        "trim_ask": "Vui lòng gửi khoảng thời gian mong muốn theo định dạng:",
        "trim_ex": "Ví dụ",
        "trim_fmt": "❌ <b>Sai định dạng.</b>\n\nHãy gửi như sau:",
        "trim_order": "❌ <b>Thời gian bắt đầu phải trước thời gian kết thúc.</b>",
        "trim_long": "❌ <b>Thời gian kết thúc vượt quá thời lượng video ({dur}).</b>",
        "trim_pick": "Chạm vào một chất lượng bên dưới để tải đoạn đã cắt:",
        "expired": "Liên kết đã hết hạn — hãy gửi lại.",
        "not_yours": "Yêu cầu này không phải của bạn.",
        "cancel_btn": "❌ Hủy",
        "dl_cancelled": "🛑 <b>Đã hủy tải xuống.</b>",
    },
    "ko": {
        "lang_set": "✅ 언어가 {name}(으)로 설정되었습니다.",
        "fetching": "🔍 <b>영상 정보를 가져오는 중...</b>",
        "avail": "사용 가능한 화질:",
        "tap": "다운로드하려면 아래에서 화질을 선택하세요:",
        "trim_btn": "✂️ 영상 자르기",
        "trim_dur": "영상 길이",
        "trim_ask": "원하는 시간 범위를 다음 형식으로 보내주세요:",
        "trim_ex": "예시",
        "trim_fmt": "❌ <b>형식이 올바르지 않습니다.</b>\n\n이렇게 보내주세요:",
        "trim_order": "❌ <b>시작 시간은 종료 시간보다 빨라야 합니다.</b>",
        "trim_long": "❌ <b>종료 시간이 영상 길이({dur})를 초과합니다.</b>",
        "trim_pick": "잘라낸 클립을 다운로드하려면 아래에서 화질을 선택하세요:",
        "expired": "링크가 만료되었습니다. 다시 보내주세요.",
        "not_yours": "본인의 요청이 아닙니다.",
        "cancel_btn": "❌ 취소",
        "dl_cancelled": "🛑 <b>다운로드가 취소되었습니다.</b>",
    },
    "ja": {
        "lang_set": "✅ 言語を{name}に設定しました。",
        "fetching": "🔍 <b>動画情報を取得中...</b>",
        "avail": "利用可能な画質:",
        "tap": "ダウンロードする画質を下から選んでください:",
        "trim_btn": "✂️ 動画トリミング",
        "trim_dur": "動画の長さ",
        "trim_ask": "希望の時間範囲を次の形式で送ってください:",
        "trim_ex": "例",
        "trim_fmt": "❌ <b>形式が正しくありません。</b>\n\nこのように送ってください:",
        "trim_order": "❌ <b>開始時間は終了時間より前にしてください。</b>",
        "trim_long": "❌ <b>終了時間が動画の長さ({dur})を超えています。</b>",
        "trim_pick": "トリミングしたクリップをダウンロードする画質を下から選んでください:",
        "expired": "リンクの有効期限が切れました。もう一度送ってください。",
        "not_yours": "これはあなたのリクエストではありません。",
        "cancel_btn": "❌ キャンセル",
        "dl_cancelled": "🛑 <b>ダウンロードをキャンセルしました。</b>",
    },
    "bn": {
        "lang_set": "✅ ভাষা {name} সেট করা হয়েছে।",
        "fetching": "🔍 <b>ভিডিওর তথ্য আনা হচ্ছে...</b>",
        "avail": "উপলব্ধ কোয়ালিটি:",
        "tap": "ডাউনলোড করতে নিচ থেকে কোয়ালিটি বেছে নিন:",
        "trim_btn": "✂️ ভিডিও ট্রিম",
        "trim_dur": "ভিডিওর দৈর্ঘ্য",
        "trim_ask": "অনুগ্রহ করে এই ফরম্যাটে সময়সীমা পাঠান:",
        "trim_ex": "উদাহরণ",
        "trim_fmt": "❌ <b>ফরম্যাট ভুল।</b>\n\nএভাবে পাঠান:",
        "trim_order": "❌ <b>শুরুর সময় শেষ সময়ের আগে হতে হবে।</b>",
        "trim_long": "❌ <b>শেষ সময় ভিডিওর দৈর্ঘ্য ({dur}) ছাড়িয়ে গেছে।</b>",
        "trim_pick": "ট্রিম করা ক্লিপ ডাউনলোড করতে নিচ থেকে কোয়ালিটি বেছে নিন:",
        "expired": "লিংকের মেয়াদ শেষ — আবার পাঠান।",
        "not_yours": "এটি আপনার অনুরোধ নয়।",
        "cancel_btn": "❌ বাতিল",
        "dl_cancelled": "🛑 <b>ডাউনলোড বাতিল করা হয়েছে।</b>",
    },
    "fil": {
        "lang_set": "✅ Naitakda ang wika sa {name}.",
        "fetching": "🔍 <b>Kinukuha ang impormasyon ng video...</b>",
        "avail": "Mga available na kalidad:",
        "tap": "I-tap ang kalidad sa ibaba para mag-download:",
        "trim_btn": "✂️ I-trim ang Video",
        "trim_dur": "Haba ng video",
        "trim_ask": "Pakipadala ang gustong saklaw ng oras sa format na ito:",
        "trim_ex": "Halimbawa",
        "trim_fmt": "❌ <b>Mali ang format.</b>\n\nIpadala nang ganito:",
        "trim_order": "❌ <b>Dapat mas maaga ang simula kaysa sa katapusan.</b>",
        "trim_long": "❌ <b>Lampas ang katapusan sa haba ng video ({dur}).</b>",
        "trim_pick": "I-tap ang kalidad sa ibaba para i-download ang na-trim na clip:",
        "expired": "Nag-expire na ang link — ipadala muli.",
        "not_yours": "Hindi sa iyo ang request na ito.",
        "cancel_btn": "❌ Kanselahin",
        "dl_cancelled": "🛑 <b>Nakansela ang download.</b>",
    },
    "ha": {
        "lang_set": "✅ An saita harshe zuwa {name}.",
        "fetching": "🔍 <b>Ana neman bayanan bidiyo...</b>",
        "avail": "Ingancin da ake da su:",
        "tap": "Danna inganci a ƙasa don saukewa:",
        "trim_btn": "✂️ Yanke Bidiyo",
        "trim_dur": "Tsawon bidiyo",
        "trim_ask": "Da fatan za a aika lokacin da kake so a wannan tsari:",
        "trim_ex": "Misali",
        "trim_fmt": "❌ <b>Tsarin bai dace ba.</b>\n\nAika haka:",
        "trim_order": "❌ <b>Lokacin farawa dole ne ya riga lokacin ƙarshe.</b>",
        "trim_long": "❌ <b>Lokacin ƙarshe ya wuce tsawon bidiyo ({dur}).</b>",
        "trim_pick": "Danna inganci a ƙasa don saukar da guntun da aka yanke:",
        "expired": "Hanyar haɗin ta ƙare — a sake aikawa.",
        "not_yours": "Wannan buƙatar ba taka ba ce.",
        "cancel_btn": "❌ Soke",
        "dl_cancelled": "🛑 <b>An soke saukewa.</b>",
    },
    "it": {
        "lang_set": "✅ Lingua impostata: {name}.",
        "fetching": "🔍 <b>Recupero delle informazioni del video...</b>",
        "avail": "Qualità disponibili:",
        "tap": "Tocca una qualità qui sotto per scaricare:",
        "trim_btn": "✂️ Taglia video",
        "trim_dur": "Durata del video",
        "trim_ask": "Invia l'intervallo di tempo desiderato nel formato:",
        "trim_ex": "Esempio",
        "trim_fmt": "❌ <b>Formato errato.</b>\n\nInvialo così:",
        "trim_order": "❌ <b>L'inizio deve precedere la fine.</b>",
        "trim_long": "❌ <b>La fine supera la durata del video ({dur}).</b>",
        "trim_pick": "Tocca una qualità qui sotto per scaricare la clip tagliata:",
        "expired": "Link scaduto — invialo di nuovo.",
        "not_yours": "Questa richiesta non è tua.",
        "cancel_btn": "❌ Annulla",
        "dl_cancelled": "🛑 <b>Download annullato.</b>",
    },
    "de": {
        "lang_set": "✅ Sprache eingestellt: {name}.",
        "fetching": "🔍 <b>Videoinformationen werden abgerufen...</b>",
        "avail": "Verfügbare Qualitäten:",
        "tap": "Tippe unten auf eine Qualität zum Herunterladen:",
        "trim_btn": "✂️ Video zuschneiden",
        "trim_dur": "Videolänge",
        "trim_ask": "Bitte sende den gewünschten Zeitbereich im Format:",
        "trim_ex": "Beispiel",
        "trim_fmt": "❌ <b>Falsches Format.</b>\n\nSende es so:",
        "trim_order": "❌ <b>Die Startzeit muss vor der Endzeit liegen.</b>",
        "trim_long": "❌ <b>Die Endzeit überschreitet die Videolänge ({dur}).</b>",
        "trim_pick": "Tippe unten auf eine Qualität, um den zugeschnittenen Clip herunterzuladen:",
        "expired": "Link abgelaufen — bitte erneut senden.",
        "not_yours": "Das ist nicht deine Anfrage.",
        "cancel_btn": "❌ Abbrechen",
        "dl_cancelled": "🛑 <b>Download abgebrochen.</b>",
    },
    "pl": {
        "lang_set": "✅ Język ustawiony: {name}.",
        "fetching": "🔍 <b>Pobieranie informacji o filmie...</b>",
        "avail": "Dostępne jakości:",
        "tap": "Kliknij jakość poniżej, aby pobrać:",
        "trim_btn": "✂️ Przytnij wideo",
        "trim_dur": "Długość filmu",
        "trim_ask": "Wyślij żądany zakres czasu w formacie:",
        "trim_ex": "Przykład",
        "trim_fmt": "❌ <b>Nieprawidłowy format.</b>\n\nWyślij tak:",
        "trim_order": "❌ <b>Czas rozpoczęcia musi być wcześniejszy niż czas zakończenia.</b>",
        "trim_long": "❌ <b>Czas zakończenia przekracza długość filmu ({dur}).</b>",
        "trim_pick": "Kliknij jakość poniżej, aby pobrać przycięty fragment:",
        "expired": "Link wygasł — wyślij go ponownie.",
        "not_yours": "To nie jest Twoje żądanie.",
        "cancel_btn": "❌ Anuluj",
        "dl_cancelled": "🛑 <b>Pobieranie anulowane.</b>",
    },
    "uk": {
        "lang_set": "✅ Мову встановлено: {name}.",
        "fetching": "🔍 <b>Отримую інформацію про відео...</b>",
        "avail": "Доступна якість:",
        "tap": "Виберіть якість нижче для завантаження:",
        "trim_btn": "✂️ Обрізка відео",
        "trim_dur": "Тривалість відео",
        "trim_ask": "Надішліть потрібний діапазон часу у форматі:",
        "trim_ex": "Приклад",
        "trim_fmt": "❌ <b>Неправильний формат.</b>\n\nНадішліть так:",
        "trim_order": "❌ <b>Початок має бути раніше за кінець.</b>",
        "trim_long": "❌ <b>Кінець перевищує тривалість відео ({dur}).</b>",
        "trim_pick": "Виберіть якість нижче, щоб завантажити обрізаний фрагмент:",
        "expired": "Посилання застаріло — надішліть його знову.",
        "not_yours": "Це не ваш запит.",
        "cancel_btn": "❌ Скасувати",
        "dl_cancelled": "🛑 <b>Завантаження скасовано.</b>",
    },
    "th": {
        "lang_set": "✅ ตั้งค่าภาษาเป็น {name} แล้ว",
        "fetching": "🔍 <b>กำลังดึงข้อมูลวิดีโอ...</b>",
        "avail": "คุณภาพที่มี:",
        "tap": "แตะคุณภาพด้านล่างเพื่อดาวน์โหลด:",
        "trim_btn": "✂️ ตัดวิดีโอ",
        "trim_dur": "ความยาววิดีโอ",
        "trim_ask": "โปรดส่งช่วงเวลาที่ต้องการในรูปแบบ:",
        "trim_ex": "ตัวอย่าง",
        "trim_fmt": "❌ <b>รูปแบบไม่ถูกต้อง</b>\n\nส่งแบบนี้:",
        "trim_order": "❌ <b>เวลาเริ่มต้องมาก่อนเวลาสิ้นสุด</b>",
        "trim_long": "❌ <b>เวลาสิ้นสุดเกินความยาววิดีโอ ({dur})</b>",
        "trim_pick": "แตะคุณภาพด้านล่างเพื่อดาวน์โหลดคลิปที่ตัดแล้ว:",
        "expired": "ลิงก์หมดอายุ — โปรดส่งอีกครั้ง",
        "not_yours": "นี่ไม่ใช่คำขอของคุณ",
        "cancel_btn": "❌ ยกเลิก",
        "dl_cancelled": "🛑 <b>ยกเลิกการดาวน์โหลดแล้ว</b>",
    },
    "uz": {
        "lang_set": "✅ Til {name} qilib o‘rnatildi.",
        "fetching": "🔍 <b>Video ma’lumotlari olinmoqda...</b>",
        "avail": "Mavjud sifatlar:",
        "tap": "Yuklab olish uchun quyidagi sifatni tanlang:",
        "trim_btn": "✂️ Videoni qirqish",
        "trim_dur": "Video davomiyligi",
        "trim_ask": "Iltimos, kerakli vaqt oralig‘ini quyidagi formatda yuboring:",
        "trim_ex": "Misol",
        "trim_fmt": "❌ <b>Format noto‘g‘ri.</b>\n\nBunday yuboring:",
        "trim_order": "❌ <b>Boshlanish vaqti tugash vaqtidan oldin bo‘lishi kerak.</b>",
        "trim_long": "❌ <b>Tugash vaqti video davomiyligidan ({dur}) oshib ketdi.</b>",
        "trim_pick": "Qirqilgan klipni yuklab olish uchun quyidagi sifatni tanlang:",
        "expired": "Havola muddati tugagan — qayta yuboring.",
        "not_yours": "Bu sizning so‘rovingiz emas.",
        "cancel_btn": "❌ Bekor qilish",
        "dl_cancelled": "🛑 <b>Yuklab olish bekor qilindi.</b>",
    },
    "kk": {
        "lang_set": "✅ Тіл {name} болып орнатылды.",
        "fetching": "🔍 <b>Бейне туралы ақпарат алынуда...</b>",
        "avail": "Қолжетімді сапа:",
        "tap": "Жүктеу үшін төменнен сапаны таңдаңыз:",
        "trim_btn": "✂️ Бейнені қию",
        "trim_dur": "Бейне ұзақтығы",
        "trim_ask": "Қажетті уақыт аралығын мына форматта жіберіңіз:",
        "trim_ex": "Мысал",
        "trim_fmt": "❌ <b>Формат дұрыс емес.</b>\n\nМына түрде жіберіңіз:",
        "trim_order": "❌ <b>Бастау уақыты аяқталу уақытынан бұрын болуы керек.</b>",
        "trim_long": "❌ <b>Аяқталу уақыты бейне ұзақтығынан ({dur}) асып кетті.</b>",
        "trim_pick": "Қиылған үзіндіні жүктеу үшін төменнен сапаны таңдаңыз:",
        "expired": "Сілтеменің мерзімі аяқталды — қайта жіберіңіз.",
        "not_yours": "Бұл сіздің сұрауыңыз емес.",
        "cancel_btn": "❌ Бас тарту",
        "dl_cancelled": "🛑 <b>Жүктеу тоқтатылды.</b>",
    },
}


def tr(lang, key, **kw):
    """Translated text for `lang`; falls back to English. `{placeholders}` are filled from kw."""
    text = (TR.get(lang) or {}).get(key) or TR["en"][key]
    return text.format(**kw) if kw else text
